### ISSUE TITLE
Consider adding C4F8 back

### ISSUE THREAD

**Issue by Trinity3e** [Artoriuz/ArtCNN#15]
I have an mpv config with lightweight processing needs here and there, especially on material that is already in high resolution, over 30 fps in framerate or if the 2x result is being slightly downscaled, C4F8 used to be below FSRCNNX in processing amount and it wouldn't drop frames, while C4F16 is uncomfortably above on the midrange gpu.
Thanks for the consideration.

**Comment by Artoriuz** [comment]
I had originally removed it to reduce the burden of having to maintain multiple models, and because it caused some nasty aliasing sometimes.

I'll retrain it with the new stack and see if it's good enough, but yeah, it seems like a lot of people are interested in C4F8 because they can't run C4F16 well. I'll see what I can do.

**Comment by Artoriuz** [comment]
Done =)

**Comment by Trinity3e** [comment]
Appreciate it! :-)

**Comment by BEST8OY** [comment]
@Artoriuz 
Hello
I didn't want to open another issue!
Are C4F8 variant gone forever this time?
